name: Build On Push/Pull Request
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - '*'
      - '!master'

  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Build It (kube-dialer)
      run: |
        mkdir artifacts
        echo 'build stuff' > artifacts/stuff.txt

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: deployment-files
        path: artifacts/  
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build   
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Run chart-testing (lint)
      run: |
        mkdir artifacts
        echo 'build stuff' > artifacts/stuff.txt
        
  advisor-scan:
    name: Advisor Scan 
    runs-on: ubuntu-latest
    needs: test   
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Download Helm
      run: |
        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 
        chmod 700 get_helm.sh 
        ./get_helm.sh


    - name: Launch Cluster
      uses: helm/kind-action@v1.0.0-alpha.3
      with:
        version: v0.7.0
        name: kruzer
        node_image: kindest/node:v1.16.4
        wait: 5m
        install_local_path_provisioner: true

    - name: Install Chart
      run: |
        helm repo add stable https://kubernetes-charts.storage.googleapis.com
        kubectl cluster-info
        kubectl create ns traefik
        helm install stable/traefik --name traefik --namespace traefik --wait

    - name: Alcide Advisor Scan
      run: |
        curl -o kube-advisor https://alcide.blob.core.windows.net/generic/stable/linux/advisor
        chmod +x kube-advisor
        ./kube-advisor --eula-sign validate cluster --namespace-include="traefik" --outfile alcide-advisor-security-report.html

    - name: Upload Alcide Advisor Scan Report
      uses: actions/upload-artifact@v1
      with:
        name: alcide-advisor-security-report.html 
        path: alcide-advisor-security-report.html  
